apiVersion: v1
kind: Service
metadata:
  name: eks-demo-mkdocs-service
  namespace: eks-demo-app
  labels:
    app: eks-demo-mkdocs-app
spec:
  selector:
    app: eks-demo-mkdocs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080